name: flutter_loc
description: A sample command-line application.
version: 1.0.4+2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  darted_cli: ^0.1.12

dev_dependencies:
  lints: ^5.1.0

executables:
  flutter_loc: "flutter_loc"
